dependencies:
- name: redis
  version: "^9.5.1"
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: queue.enabled
- name: postgresql
  version: 6.5.8
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
